0 bash -c 'python -u -m swissclim_evaluations.cli --config "config/dev/full_verification_run.yaml" > logs/full_verification_run.log 2>&1'
1 bash -c 'python -u -m swissclim_evaluations.cli --config "config/dev/full_verification_run_prob.yaml" > logs/full_verification_run_prob.log 2>&1'
2 bash -c 'python -u -m swissclim_evaluations.cli --config "config/dev/test_multilead_det.yaml" > logs/test_multilead_det.log 2>&1'
3 bash -c 'python -u -m swissclim_evaluations.cli --config "config/dev/test_multilead_prob.yaml" > logs/test_multilead_prob.log 2>&1'
