models:
  - output/test_multilead
  - output/test_multilead_2

labels:
  - Test Run 1
  - Test Run 2

output_root: output/intercomparison_multilead

modules: [maps, hist, kde, spectra, vprof, metrics, ets, ssim, prob]

max_map_panels: 4
max_crps_map_panels: 4
