## Swiss AI container definition for CSCS
## IMPORTANT: This template assumes the repository resides at
##   /capstor/store/cscs/swissai/a122/{{username}}/SwissClim_Evaluations
## See README Quickstart step 0 if you cloned elsewhere (adjust image/workdir/mount paths accordingly).
## If the container is not available on the system, it can be built with:
##   podman build -t swissclim-eval .
##   enroot import -x mount -o /capstor/store/cscs/swissai/a122/{{username}}/SwissClim_Evaluations/tools/swissclim-eval.sqsh podman://swissclim-eval

image = "/capstor/store/cscs/swissai/a122/{{username}}/SwissClim_Evaluations/tools/swissclim-eval.sqsh"
workdir = "/capstor/store/cscs/swissai/a122/{{username}}/SwissClim_Evaluations"
mounts = [
    "/users",
    "/capstor",
    "/iopsstor",
    "/capstor/store/cscs/swissai/a122/{{username}}/SwissClim_Evaluations",
]
writable = true

[env]
LD_LIBRARY_PATH = "/usr/local/cuda/lib64:/opt/hpcx/ucc/lib/:/opt/hpcx/ucx/lib:/usr/local/cuda/compat/lib.real:/external/lib:/usr/local/lib/python3.10/dist-packages/torch/lib:/usr/local/lib/python3.10/dist-packages/torch_tensorrt/lib:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64"
XDG_CONFIG_HOME = "/root/.config"
CONDA_AUTO_ACTIVATE_BASE = "false"
CONDA_DEFAULT_ENV = ""
GOGC = "off"
OMP_WAIT_POLICY = "ACTIVE"
OMP_PLACES = "cores"
OMP_PROC_BIND = "close"
OMP_MAX_ACTIVE_LEVELS = "1"
